# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check the documentation for more details about how to
# customize your build variants and see how to integrate with your IDE.
# For more details on building your Android app with Gradle,
# read the documentation at https://developer.android.com/build/configure-your-build.

# The following line is optional.
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are being used
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
# Enable jetpack compose
android.enableJetpackCompose=true
# Gradle build cache
org.gradle.caching=true
# Parallel builds
org.gradle.parallel=true
# Increased heap for gradle daemon
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m

# Android build features
android.defaults.buildfeatures.buildconfig=true
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false

# Optimization
android.enableMinifyInLibraries=false
